CREATE TABLE IF NOT EXISTS 2020_participants (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(25) NULL,
    rollNo VARCHAR(25) NOT NULL,
    projects VARCHAR(1000) NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 2020_live (
    isLive VARCHAR(5) NOT NULL default "false"
);

INSERT INTO 2020_live (isLive) VALUES ("false");